-- A´Ô [n] 2´Ü°è

BEGIN TRAN
UPDATE	[TABLE1]
SET		USERID = n, [CONDITION]
FROM		[TABLE1]										A
			INNER JOIN (	SELECT top(200)*
								FROM [TABLE1]
								WHERE [CONDITION]
								AND USERID = 'm'
								AND [CONDITION]     							)	B ON A.PRODUCTID = B.PRODUCTID
where [CONDITION];
COMMIT TRAN
ROLLBACK TRAN



-- B´Ô [m] 1´Ü°è
BEGIN TRAN
UPDATE	[TABLE1]
SET		USERID = m, [CONDITION]
FROM		[TABLE1]											A
			INNER JOIN (	SELECT TOP(1000)*
								FROM [TABLE1]
								WHERE [CONDITION]1
								AND [CONDITION]
								AND [CONDITION]
								and [CONDITION]					)	B ON A.PRODUCTID = B.PRODUCTID
where [CONDITION];
COMMIT TRAN
ROLLBACK TRAN
